### PR TITLE
CHANGELOG: and links to references

### PR DESCRIPTION
**Pull request by miraclx**
GitHub doesn't auto-link references to issues/PRs in files other than README.md

https://docs.github.com/en/github/writing-on-github/autolinked-references-and-urls#issues-and-pull-requests
Screenshot_20210208_231343

### CODE REVIEW

**Comment by tarkah** [comment]
Ahh, nice catch. Thanks!

**Comment by miraclx** [comment]
This seems to have unintended side effects in the new release doc

### Now

Screenshot_20210209_002415

### Before

Screenshot_20210209_002743

It seems, in release docs, auto-linking refs work just fine, but not in the CHANGELOG.md file directly.

You could just edit the release doc but there's gotta be a better way to retain references when viewing the CHANGELOG.md directly vs when you look at the release page

**Comment by tarkah** [comment]
Yeah, I'll try to be better about removing the brackets when copying / pasting into the release. Worst case, the links still work so I'm not too concerned.

**Comment by miraclx** [comment]
Oh, I assumed it was autogenerated by `github-actions`. It still would require some extra effort on your part, so it's best to iron that out.

I used reference-style links to make it easier to read without md rendering.

You can try using the full-format to see if that renders correctly

``` diff
- [#54]
+ [#54][#54]
```

Or just using the full thing

``` diff
- [#54]
+ [#54](https://github.com/tarkah/tickrs/pull/54)
...
...
- [#54]: https://github.com/tarkah/tickrs/pull/54
```

**Pull request merged**
