### PR TITLE
event: fix backtab behaviour on config pane

### PR DESCRIPTION
**Pull request by miraclx**
My bad on #104, #70 takes a while to get used to.

### CODE REVIEW

**Comment by tarkah** [comment]
Good thing this isn't really too critical :P

**Comment by tarkah** [comment]
@miraclx Can you make sure to update the CHANGELOG on future changes, especially like this where it fixes a bug that someone might encounter. I've gone ahead and updated it on master.

**Comment by miraclx** [comment]
Got it, will do!

**Comment by tarkah** [comment]
@miraclx I saw you just found / starred Ajour! We could use some contributions from you there as well :)

**Comment by miraclx** [comment]
Oh...

Yeah, I was really stunned by how beautiful it is. I sure stand corrected on the state of pure-rust GUI libraries. I was going to use Qt bindings for my next GUI projects *([freyr-gui](https://github.com/miraclx/freyr-gui) for instance)* but now, I'm inspired to actually use iced or something similar.

And yeah, I'd love to contribute but unfortunately I don't play WoW, I never get past the `Welcome to Ajour (Select Directory)` screen.

But great work, it looks stunning from the screenshots!

**Comment by tarkah** [comment]
Yeah, Casper, the creator, has a really good eye and has made it look really nice. There's definitely still a lot of shortcomings with iced, but it's worked out since we set out to keep Ajour minimalistic from the get go.

Once there's more mature support for overlay widgets, iced will be more enjoyable to work with.

**Pull request merged**
