### PR TITLE
allow chart scroll with side pane open

### PR DESCRIPTION
**Pull request by miraclx**
Allow chart scrolling when a side pane (options or config) is open

This merges #105, and is in ref to #93

### CODE REVIEW

**Comment by tarkah** [comment]
You can rebase this, #105 is merged

**Comment by tarkah** [comment]
Any reason this is still a draft?

**Comment by miraclx** [comment]
For feat/kagi, not really. But I'm thinking the PR should support chart scrolling for any side pane.

Including the options pane. That can be another PR on master though.

What do you think?

**Comment by tarkah** [comment]
I agree, lets just roll that out in here so it's good to go when I release #93

**Pull request merged**
